name: ts_annotator
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0=h57928b3_2
  - _openmp_mutex=4.5=2_gnu
  - affine=2.4.0=pyhd8ed1ab_1
  - aom=3.9.1=he0c23c2_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - attrs=25.4.0=pyhcf101f3_1
  - blas=1.0=mkl
  - blosc=1.21.6=hfd34d9b_1
  - bottleneck=1.4.2=py311h540bb41_1
  - brotlicffi=1.2.0.0=py311h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py311h02ab6af_1
  - charset-normalizer=3.4.4=py311haa95532_0
  - click=8.3.1=pyha7b4d00_1
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311h214f63a_0
  - cuda-cccl=12.9.27=0
  - cuda-cccl_win-64=12.9.27=0
  - cuda-cudart=12.4.127=0
  - cuda-cudart-dev=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-libraries-dev=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvrtc-dev=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.79=0
  - cuda-runtime=12.4.1=0
  - cuda-version=12.9=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.17=py311h5dfdfe8_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h885b0b7_4
  - filelock=3.20.0=py311haa95532_0
  - fiona=1.10.1=py311h8db5f30_6
  - fonttools=4.61.0=py311h02ab6af_0
  - freetype=2.14.1=h57928b3_0
  - freexl=2.0.0=hf297d47_2
  - fsspec=2025.10.0=py311h4442805_0
  - geos=3.14.1=hdade9fe_0
  - geotiff=1.7.4=h73469f5_4
  - giflib=5.2.2=h7edc060_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.2=py311h8598115_0
  - gst-plugins-base=1.24.12=h91a6125_1
  - gstreamer=1.24.12=hfb93a4f_1
  - gstreamer-orc=0.4.41=ha00e802_0
  - icu=75.1=he0c23c2_0
  - idna=3.11=py311haa95532_0
  - importlib-metadata=8.7.0=py311haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.8.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py311haa95532_0
  - joblib=1.5.2=py311haa95532_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - khronos-opencl-icd-loader=2025.07.22=h79b28c9_0
  - kiwisolver=1.4.9=py311h03f52e7_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libarchive=3.8.2=gpl_h26aea39_100
  - libavif16=1.3.0=he916da2_2
  - libblas=3.9.0=20_win64_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.9.0=20_win64_mkl
  - libclang13=20.1.8=default_hccbf073_0
  - libcublas=12.4.5.8=0
  - libcublas-dev=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufft-dev=11.2.1.3=0
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcurl=8.17.0=h43ecb02_1
  - libcusolver=11.6.1.9=0
  - libcusolver-dev=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libcusparse-dev=12.3.1.170=0
  - libde265=1.0.15=h91493d7_0
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_16
  - libgdal-core=3.12.1=h4c6072a_0
  - libglib=2.86.3=h0c9aed9_0
  - libgomp=15.2.0=h8ee18e1_16
  - libheif=1.19.7=gpl_h2684147_100
  - libhwloc=2.12.1=default_h4379cf1_1003
  - libhwy=1.3.0=ha71e874_1
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libjxl=0.11.1=hac9b6f3_5
  - libkml=1.3.0=h68a222c_1022
  - liblapack=3.9.0=20_win64_mkl
  - libllvm20=20.1.8=h3aa9ab2_0
  - liblzma=5.8.1=h2466b09_2
  - liblzma-devel=5.8.1=h2466b09_2
  - libnpp=12.2.5.30=0
  - libnpp-dev=12.2.5.30=0
  - libnvfatbin=12.9.82=0
  - libnvfatbin-dev=12.9.82=0
  - libnvjitlink=12.4.127=0
  - libnvjitlink-dev=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libnvjpeg-dev=12.3.1.117=0
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.53=h7351971_0
  - libprotobuf=5.29.3=h65a231f_1
  - librttopo=1.1.0=haa95264_20
  - libsodium=1.0.20=hc70643c_0
  - libspatialite=5.1.0=gpl_h0cd62ae_119
  - libsqlite=3.51.1=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.1=h8f73337_1
  - libtorch=2.5.1=cpu_mkl_h9002858_104
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=ha29bfb0_0
  - libxml2-16=2.15.1=h06f855e_0
  - libxml2-devel=2.15.1=ha29bfb0_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.10.0=h2466b09_1
  - lzo=2.10=h6a83c73_1002
  - markupsafe=3.0.2=py311h827c3e9_0
  - matplotlib=3.10.7=py311haa95532_0
  - matplotlib-base=3.10.7=py311h26e45b9_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - minizip=4.0.10=h9fa1bad_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py311h827c3e9_2
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py311haa95532_0
  - muparser=2.3.5=he0c23c2_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.6.1=py311haa95532_0
  - numexpr=2.11.0=py311hdb065b2_0
  - opencl-headers=2025.07.22=h885b0b7_0
  - openjpeg=2.5.4=h56d5a42_1
  - openssl=3.6.0=h725018a_0
  - opentelemetry-api=1.38.0=py311haa95532_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h42c1672_1
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.47=hd2b5f0e_0
  - pillow=12.0.0=py311h17b8079_2
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - proj=9.7.1=h7b1ce8f_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py311hf893f09_0
  - pthread-stubs=0.3=h3c9f919_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.23=py311haa95532_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=py311haa95532_1
  - python=3.11.14=h0159041_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytorch-cuda=12.4=h3fd98bf_7
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=py311haa95532_0
  - pywin32=311=py311hefeebc8_1
  - pyyaml=6.0.3=py311h3f79411_0
  - pyzmq=27.1.0=py311hb77b9c8_0
  - rasterio=1.4.4=py311h54359c7_2
  - rav1e=0.7.1=ha073cba_3
  - requests=2.32.5=py311haa95532_1
  - scikit-learn=1.7.2=py311h7f7e138_1
  - setuptools=80.9.0=py311haa95532_0
  - shapely=2.1.2=py311h362461e_2
  - sip=6.12.0=py311h706e071_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.5.1=h8cc25b3_2
  - snappy=1.2.2=h7fa0ca8_1
  - snuggs=1.4.7=pyhd8ed1ab_2
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=3.1.2=hac47afa_0
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=3.5.0=py311h4442805_1
  - tk=8.6.15=hf199647_0
  - tornado=6.5.3=py311h3485c13_0
  - tqdm=4.67.1=py311h4442805_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - uriparser=0.9.8=h5a68840_0
  - urllib3=2.6.1=py311haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_1
  - x265=3.5=h2d74725_3
  - xerces-c=3.3.0=he0c23c2_0
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xz=5.8.1=h208afaa_2
  - xz-tools=5.8.1=h2466b09_2
  - yaml=0.2.5=h6a83c73_3
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=py311haa95532_0
  - zlib=1.3.1=h02ab6af_0
  - zlib-ng=2.3.2=h5112557_0
  - zstd=1.5.7=h534d264_6
  - pip:
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - beartype==0.22.8
      - blis==1.3.3
      - catalogue==2.0.10
      - cleanlab==2.7.1
      - cloudpathlib==0.23.0
      - cloudpickle==3.1.2
      - confection==0.1.5
      - cymem==2.0.13
      - fastai==2.8.5
      - fastcore==1.8.17
      - fastdownload==0.0.7
      - fastprogress==1.0.3
      - fasttransform==0.0.2
      - geopandas==1.1.2
      - hydra-core==1.3.2
      - imbalanced-learn==0.14.0
      - iniconfig==2.3.0
      - iopath==0.1.10
      - ipywidgets==8.1.8
      - jupyterlab-widgets==3.0.16
      - llvmlite==0.46.0
      - loguru==0.7.3
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - murmurhash==1.0.15
      - numba==0.63.1
      - numpy==1.26.4
      - omegaconf==2.3.0
      - pluggy==1.6.0
      - plum-dispatch==2.6.0
      - portalocker==3.2.0
      - preshed==3.0.12
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pyogrio==0.12.1
      - pyproj==3.7.2
      - pyqt6==6.6.1
      - pyqt6-qt6==6.6.1
      - pyqt6-sip==13.10.3
      - pyqtgraph==0.14.0
      - pytest==9.0.2
      - python-dotenv==1.2.1
      - pyts==0.13.0
      - rich==14.2.0
      - sam-mosaic==2.0.0
      - sam2==1.1.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - sits==0.1.0
      - smart-open==7.5.0
      - spacy==3.8.11
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.2
      - sympy==1.13.1
      - termcolor==3.2.0
      - thinc==8.3.10
      - torch==2.6.0+cu124
      - torchaudio==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - tsai==0.4.1
      - tslearn==0.7.0
      - typer-slim==0.20.0
      - typing-inspection==0.4.2
      - wasabi==1.1.3
      - weasel==0.4.3
      - widgetsnbextension==4.0.15
      - win32-setctime==1.2.0
      - wrapt==2.0.1
prefix: C:\Users\Admin\anaconda3\envs\ts_annotator
